# Generated by Django 2.1.1 on 2018-09-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersProjects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='projects',
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(related_name='projects', to='usersProjects.Technology'),
        ),
    ]
