# Generated by Django 2.1.1 on 2018-10-17 12:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usersProjects', '0003_auto_20181017_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects_id', models.ManyToManyField(related_name='_like_projects_id_+', to='usersProjects.Project')),
                ('users_id', models.ManyToManyField(related_name='_like_users_id_+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
