# Generated by Django 2.1.1 on 2018-10-17 12:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersProjects', '0004_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='projects_id',
            field=models.ManyToManyField(related_name='projects_id', to='usersProjects.Project'),
        ),
        migrations.AlterField(
            model_name='like',
            name='users_id',
            field=models.ManyToManyField(related_name='users_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
