# Generated by Django 2.1.1 on 2018-09-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absUser', '0002_remove_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
