# Generated by Django 2.1.1 on 2018-10-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absUser', '0003_auto_20180912_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
